Repository TokTok/qTox, pull requests merged in 2024-11, with the labels that each got.

#43 chore: Disable restyled for now
  .restyled.yaml
Labels: chore

#44 chore(ci): Lower cirrus ci timeout
  .cirrus.yml
Labels: chore

#46 chore: Add alpine docker build to CI.
  .cirrus.yml
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  buildscripts/docker/Dockerfile.alpine
  cmake/Dependencies.cmake
  src/appmanager.cpp
  src/net/updatecheck.cpp
  src/widget/form/settings/aboutform.cpp
Labels: chore

#41 chore: Add new error enumerator for conference join.
  util/src/toxcoreerrorparser.cpp
Labels: chore

#48 chore: add developer to appstream metainfo
  res/io.github.qtox.qTox.appdata.xml
Labels: chore

#47 chore: Cancel old release-check runs when pushing new commits.
  .github/workflows/release.yml
Labels: chore

#52 cleanup: Fix a few more deprecation warnings.
  audio/src/backend/openal.cpp
  src/model/about/aboutfriend.cpp
  src/model/notificationgenerator.cpp
  src/model/sessionchatlog.cpp
  src/net/avatarbroadcaster.cpp
  src/nexus.cpp
  src/persistence/paths.cpp
  src/persistence/settings.cpp
  src/persistence/settingsserializer.cpp
  src/video/cameradevice.cpp
  src/video/camerasource.cpp
  src/widget/about/aboutfriendform.cpp
  src/widget/form/chatform.cpp
  src/widget/form/genericchatform.cpp
  src/widget/form/groupinvitewidget.cpp
  src/widget/form/profileform.cpp
  src/widget/form/settings/aboutform.cpp
  src/widget/friendlistwidget.cpp
  src/widget/friendwidget.cpp
  src/widget/passwordedit.cpp
  src/widget/tool/movablewidget.cpp
  src/widget/translator.cpp
  src/widget/widget.cpp
  test/chatlog/chatlinestorage_test.cpp
Labels: cleanup

#54 chore: Enable restyled code formatter.
  .restyled.yaml
  src/platform/camera/avfoundation.h
  src/platform/timer_osx.cpp
  src/video/cameradevice.cpp
  src/video/videoframe.cpp
  src/widget/contentdialog.cpp
  src/widget/flowlayout.h
  src/widget/loginscreen.cpp
  src/widget/loginscreen.h
  src/widget/tool/messageboxmanager.cpp
  src/widget/tool/screengrabberchooserrectitem.cpp
Labels: chore

#50 chore: Reinstate deploy scripts.
  .ci-scripts/build-qtox-macos.sh
  .github/actions/build-docker-image/action.yml
  .github/actions/load-docker-image/action.yml
  .github/workflows/build-test-deploy.yaml
  .github/workflows/commit-format.yaml
  .github/workflows/docker.yml
  .restyled.yaml
  CMakeLists.txt
  INSTALL.md
  buildscripts/build_aitool_linux.sh
  buildscripts/build_ffmpeg.sh
  buildscripts/build_glfw.sh
  buildscripts/build_ldqt_linux.sh
  buildscripts/build_qt_windows.sh
  buildscripts/build_sqlcipher.sh
  buildscripts/build_toxcore.sh
  buildscripts/build_toxcore_linux.sh
  buildscripts/build_utils.sh
  buildscripts/build_vpx.sh
  buildscripts/docker/Dockerfile.almalinux
  buildscripts/docker/Dockerfile.archlinux
  buildscripts/docker/Dockerfile.debian
  buildscripts/docker/Dockerfile.debian_old
  buildscripts/docker/Dockerfile.fedora
  buildscripts/docker/Dockerfile.flatpak_builder
  buildscripts/docker/Dockerfile.opensuse
  buildscripts/docker/Dockerfile.ubuntu_lts
  buildscripts/docker/Dockerfile.windows_builder
  buildscripts/download/common.sh
  buildscripts/download/download_ffmpeg.sh
  buildscripts/download/download_glfw.sh
  buildscripts/download/download_ldqt.sh
  buildscripts/download/download_openssl.sh
  buildscripts/download/download_qrencode.sh
  buildscripts/download/download_qt.sh
  buildscripts/download/download_sodium.sh
  buildscripts/download/download_sqlcipher.sh
  buildscripts/download/download_toxcore.sh
  buildscripts/download/download_vpx.sh
  cmake/Dependencies.cmake
  docker-compose.yml
  flatpak/io.github.qtox.qTox.json
  osx/Brewfile
  osx/Brewfile-DepBuildDeps
  src/core/corefile.cpp
  src/widget/form/genericchatform.cpp
  windows/cross-compile/build.sh
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#57 chore: Reduce the amount of CI builds we do.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#59 chore: Add back the 32 bit windows build.
  .github/workflows/build-test-deploy.yaml
  docker-compose.yml
Labels: chore

#60 cleanup: Delete compatibility recursive mutex.
  audio/src/backend/alsink.cpp
  audio/src/backend/alsink.h
  audio/src/backend/alsource.cpp
  audio/src/backend/alsource.h
  audio/src/backend/openal.cpp
  audio/src/backend/openal.h
  src/core/core.cpp
  src/core/core.h
  src/core/coreav.cpp
  src/core/coreav.h
  src/core/corefile.cpp
  src/core/corefile.h
  src/persistence/offlinemsgengine.cpp
  src/persistence/offlinemsgengine.h
  src/persistence/settings.cpp
  src/persistence/settings.h
  util/CMakeLists.txt
  util/include/util/compatiblerecursivemutex.h
Labels: cleanup

#62 cleanup: Delete all qt5 version checks.
  src/appmanager.cpp
  src/chatlog/chatwidget.cpp
  src/model/sessionchatlog.cpp
  src/persistence/history.cpp
  src/widget/contentdialog.cpp
  src/widget/emoticonswidget.cpp
  src/widget/form/genericchatform.cpp
  src/widget/form/loadhistorydialog.cpp
  src/widget/form/searchsettingsform.cpp
  src/widget/genericchatitemlayout.h
  src/widget/tool/activatedialog.h
  src/widget/tool/croppinglabel.cpp
  src/widget/widget.cpp
Labels: cleanup

#64 chore: Fix macos deploy build rpath corrector.
  osx/macfixrpath
Labels: chore

#63 chore: Add Android apk build.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  android/cross-compile/build.sh
  android/keystore.jks
  buildscripts/docker/Dockerfile.android_builder
  cmake/Dependencies.cmake
  cmake/Installation.cmake
  docker-compose.yml
  src/ipc.cpp
  src/ipc.h
  src/video/cameradevice.cpp
  src/widget/widget.cpp
Labels: chore

#65 chore: Upload apks to the release and nightly tags.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#68 chore: Fix apk path so release uploads actually work.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#71 chore: Revive spell check feature.
  buildscripts/docker/Dockerfile.alpine
  buildscripts/docker/Dockerfile.archlinux
  buildscripts/docker/Dockerfile.fedora
  cmake/Dependencies.cmake
  simple_make.sh
  src/widget/form/genericchatform.cpp
Labels: chore

#70 cleanup: Minimise direct dependencies on core.h.
  src/chatlog/chatwidget.cpp
  src/core/corefile.h
  src/model/chatroom/friendchatroom.cpp
  src/model/friend.h
  src/model/ichatlog.h
  src/model/imessagedispatcher.h
  src/persistence/history.cpp
  src/persistence/offlinemsgengine.h
  src/persistence/profile.h
  src/widget/categorywidget.h
  src/widget/form/chatform.h
  src/widget/form/filesform.cpp
  src/widget/form/filesform.h
  src/widget/friendlistlayout.h
  src/widget/friendlistwidget.cpp
  src/widget/friendlistwidget.h
  src/widget/widget.h
  test/model/friendmessagedispatcher_test.cpp
  test/model/groupmessagedispatcher_test.cpp
  test/widget/filesform_test.cpp
Labels: cleanup

#97 fix: Don't show unicode replacement boxes on unsupported languages.
  src/widget/form/settings/generalform.cpp
  src/widget/form/settings/generalform.h
  src/widget/form/settingswidget.cpp
  translations/ar.ts
  translations/be.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: bug

#100 chore: Give Cirrus more CPUs to build qtox.
  .cirrus.yml
Labels: chore

#101 chore: Use built docker image from docker hub.
  .github/workflows/build-test-deploy.yaml
  docker-compose.yml
Labels: chore

#102 chore: Use tag docker images instead of repos.
  .ci-scripts/build-osx-deps.sh
  .ci-scripts/build-qtox-linux.sh
  .ci-scripts/build-qtox-macos.sh
  .github/workflows/build-test-deploy.yaml
  docker-compose.yml
  osx/Brewfile
  osx/Brewfile-DepBuildDeps
  src/widget/qrwidget.cpp
Labels: chore

#93 cleanup: Fix typo "groupOnlyNotfiyWhenMentioned"
  src/widget/form/settings/userinterfaceform.cpp
  src/widget/form/settings/userinterfaceform.h
  src/widget/form/settings/userinterfacesettings.ui
Labels: cleanup

#103 chore: Cache built macos dependencies in CI.
  .ci-scripts/build-osx-deps.sh
  .github/workflows/build-test-deploy.yaml
Labels: chore

#96 fix: Fixed the style selector in UI settings.
  src/widget/form/settings/userinterfaceform.cpp
  src/widget/form/settings/userinterfaceform.h
Labels: bug

#107 chore: Use separate cache keys for the jobs using ccache.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#95 fix: Don't create huge font weights in themes.
  src/widget/style.cpp
Labels: bug

#105 fix: Make checkboxes more visible on wayland.
  themes/default/window/general.css
Labels: bug

#94 fix(security): Do a better job of anonymising the log output.
  src/appmanager.cpp
Labels: bug, security

#111 cleanup: Make filesform.h and toxuri.cpp parseable by Linguist.
  CMakeLists.txt
  src/BUILD.bazel
  src/net/toxuri.cpp
  src/widget/form/filesform.cpp
  src/widget/form/filesform.h
  src/widget/form/filetransferlist.h
Labels: cleanup

#113 docs: Set translations for conference strings to unfinished.
  translations/ar.ts
  translations/be.ts
  translations/bg.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/hr.ts
  translations/hu.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/sk.ts
  translations/sl.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: documentation

#115 cleanup: Delete docker image actions.
  .github/actions/build-docker-image/action.yml
  .github/actions/load-docker-image/action.yml
Labels: cleanup

#117 cleanup: Make tox error code logging originate from calling code.
  util/include/util/toxcoreerrorparser.h
  util/src/toxcoreerrorparser.cpp
Labels: cleanup

#114 feat: Add new translations: Bengali, Latvian, Flemish, Vietnamese.
  cmake/Testing.cmake
  src/widget/form/settings/generalform.cpp
  src/widget/form/settings/generalform.h
  test/BUILD.bazel
  test/widget/form/settings/generalform_test.cpp
  tools/update-translation-files.sh
  translations/CMakeLists.txt
  translations/translations.qrc
Labels: enhancement

#73 cleanup: Unify source to have prefix-`const` everywhere.
  .clang-format
  audio/src/backend/openal.cpp
  src/chatlog/chatwidget.cpp
  src/chatlog/content/filetransferwidget.cpp
  src/chatlog/content/filetransferwidget.h
  src/chatlog/textformatter.cpp
  src/core/core.cpp
  src/core/coreav.cpp
  src/core/coreext.h
  src/core/toxid.cpp
  src/model/conferencemessagedispatcher.cpp
  src/model/conferencemessagedispatcher.h
  src/model/friendmessagedispatcher.cpp
  src/model/friendmessagedispatcher.h
  src/model/message.cpp
  src/model/notificationgenerator.cpp
  src/model/notificationgenerator.h
  src/model/sessionchatlog.cpp
  src/persistence/db/upgrades/dbupgrader.cpp
  src/persistence/globalsettingsupgrader.cpp
  src/persistence/history.cpp
  src/persistence/history.h
  src/persistence/iconferencesettings.h
  src/persistence/offlinemsgengine.cpp
  src/persistence/offlinemsgengine.h
  src/persistence/personalsettingsupgrader.cpp
  src/persistence/settings.cpp
  src/persistence/settings.h
  src/widget/form/conferenceform.cpp
  src/widget/widget.cpp
  test/dbutility/src/dbutility.cpp
  test/model/conferencemessagedispatcher_test.cpp
  test/model/friendlistmanager_test.cpp
  test/model/notificationgenerator_test.cpp
  test/model/sessionchatlog_test.cpp
  test/persistence/offlinemsgengine_test.cpp
  util/include/util/strongtype.h
Labels: cleanup

#72 cleanup: Don't use `<header.h>` for local includes.
  src/BUILD.bazel
  src/chatlog/content/filetransferwidget.ui
  src/core/toxcall.h
  src/mainwindow.ui
  src/model/status.cpp
  src/widget/form/profileform.ui
Labels: cleanup

#121 fix: remove extra newline in log
  src/widget/form/settings/avform.cpp
Labels: bug

#123 docs: Update readme to say we're active on qTox again.
  .restyled.yaml
  README.md
Labels: documentation

#98 feat: Add desktop notifications support on Linux.
  CMakeLists.txt
  android/cross-compile/build.sh
  cmake/Dependencies.cmake
  src/BUILD.bazel
  src/platform/desktop_notifications/desktopnotify.cpp
  src/platform/desktop_notifications/desktopnotify.h
  windows/cross-compile/build.sh
Labels: enhancement

#127 chore: Add arch and build type to Android matrix.
  .ci-scripts/build-qtox-linux.sh
  .github/workflows/build-test-deploy.yaml
  .restyled.yaml
  android/cross-compile/build.sh
  docker-compose.yml
  flatpak/build.sh
Labels: chore

#125 style: Reformat SQL query code a bit to reduce right-alignment.
  src/persistence/history.cpp
Labels: style

#124 cleanup: Add spdx license header to our only ObjC++ file.
  src/platform/camera/avfoundation.mm
Labels: cleanup

#130 fix: Add Caucasian Albanian Script writing system mapping.
  src/widget/form/settings/generalform.cpp
Labels: bug

#132 cleanup: Reformat all the cmake files with cmake-format.
  .restyled.yaml
  CMakeLists.txt
  audio/CMakeLists.txt
  cmake/CheckAtomic.cmake
  cmake/Dependencies.cmake
  cmake/Installation.cmake
  cmake/Testing.cmake
  cmake/warnings/CMakeLists.txt
  test/dbutility/CMakeLists.txt
  test/mock/CMakeLists.txt
  translations/CMakeLists.txt
  util/CMakeLists.txt
Labels: cleanup

#135 fix: Fix use-after-free bug in desktop notifications.
  CMakeLists.txt
  INSTALL.md
  src/platform/desktop_notifications/desktopnotify.cpp
Labels: bug

#110 refactor: Make code less dependent on the Settings object.
  .ci-scripts/build-qtox-linux.sh
  CMakeLists.txt
  cmake/Testing.cmake
  src/nexus.cpp
  src/persistence/profile.cpp
  src/persistence/profile.h
  src/persistence/settings.cpp
  src/persistence/settings.h
  src/persistence/toxsave.cpp
  src/widget/form/settings/userinterfaceform.cpp
  src/widget/loginscreen.cpp
  src/widget/loginscreen.h
  src/widget/style.cpp
  src/widget/style.h
  src/widget/tool/profileimporter.cpp
  src/widget/tool/profileimporter.h
  src/widget/widget.cpp
  test/BUILD.bazel
  test/resources/images/loginscreen.png
  test/resources/test_data.qrc
  test/widget/loginscreen_test.cpp
Labels: refactor

#137 chore: Fix android nightly/release upload.
  .github/workflows/build-test-deploy.yaml
  android/cross-compile/build.sh
Labels: chore

#138 chore: Build windows debug builds with a console.
  CMakeLists.txt
  windows/cross-compile/build.sh
Labels: chore

#139 chore: Add macos-14 build for Apple Silicon.
  .ci-scripts/build-osx-deps.sh
  .ci-scripts/build-qtox-macos.sh
  .github/workflows/build-test-deploy.yaml
  osx/Brewfile-DepBuildDeps
Labels: chore

#141 chore: Trigger deploy workflows on release.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#142 chore: Also build/test/deploy on pre-releases.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#143 chore: Third attempt at fixing prerelease building.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#144 chore: Undo the release deploy stuff.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#146 cleanup: Fix typo in spellcheck CMake option.
  CMakeLists.txt
Labels: cleanup

#147 chore: Add version check for toxcore.
  cmake/Dependencies.cmake
Labels: chore

#148 fix(security): Only allow printable characters in incoming messages.
  src/core/toxstring.cpp
  src/core/toxstring.h
  test/core/toxstring_test.cpp
Labels: bug, security

#150 fix: Correct the tab completion regex so it works with Qt6.
  src/widget/form/tabcompleter.cpp
Labels: bug

#151 cleanup: Use function pointer slots instead of old style strings.
  src/widget/about/aboutfriendform.cpp
  src/widget/contentdialog.cpp
  src/widget/form/chatform.cpp
  src/widget/form/conferenceform.cpp
  src/widget/form/genericchatform.cpp
  src/widget/form/genericchatform.h
  src/widget/form/setpassworddialog.cpp
  src/widget/tool/flyoutoverlaywidget.cpp
  src/widget/tool/screenshotgrabber.cpp
  src/widget/widget.cpp
Labels: cleanup

#152 chore: Add CMake presets for IDEs (now) and CI (later).
  CMakePresets.json
  src/BUILD.bazel
Labels: chore

#155 docs: Translations update from Hosted Weblate
  translations/ru.ts
Labels: documentation

#157 chore: update update url to toktok
  src/net/updatecheck.cpp
Labels: chore

#159 fix: memory error on exit
  src/widget/form/genericchatform.cpp
Labels: bug

#161 fix: Allow building qtox without update check.
  .ci-scripts/build-qtox-linux.sh
  src/net/updatecheck.cpp
  src/net/updatecheck.h
  src/widget/form/settings/aboutform.cpp
  src/widget/form/settingswidget.cpp
  src/widget/widget.cpp
Labels: bug

#163 docs: Translations update from Hosted Weblate
  translations/es.ts
Labels: documentation

#158 feat: Add a Qt object tree view in the debug widget.
  CMakeLists.txt
  src/BUILD.bazel
  src/model/debug/debugobjecttreemodel.cpp
  src/model/debug/debugobjecttreemodel.h
  src/widget/form/chatform.cpp
  src/widget/form/chatform.h
  src/widget/form/debug/debuglog.cpp
  src/widget/form/debug/debuglog.h
  src/widget/form/debug/debuglog.ui
  src/widget/form/debug/debugobjecttree.cpp
  src/widget/form/debug/debugobjecttree.h
  src/widget/form/debug/debugobjecttree.ui
  src/widget/form/debugwidget.cpp
  src/widget/form/debugwidget.h
  src/widget/form/genericchatform.cpp
  src/widget/form/settings/genericsettings.cpp
  src/widget/form/settings/genericsettings.h
  src/widget/friendlistwidget.cpp
  src/widget/widget.cpp
Labels: enhancement

#165 chore: Run deploy workflows on tags.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#169 chore: Add modern interactive issue template.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: chore
