Repository TokTok/qTox, pull requests merged in 2024-12, with the labels that each got.

#176 fix: Typo fix unavaliable -> unavailable.
  android/cross-compile/build.sh
  src/widget/form/profileform.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: bug

#181 chore: Make About -> File bug link use the new form-based bug report.
  .github/ISSUE_TEMPLATE/bug.yaml
  src/widget/form/settings/aboutform.cpp
  src/widget/form/settings/aboutform.h
  src/widget/form/settingswidget.cpp
Labels: chore

#182 chore: Add a debug build for Android APK.
  .github/workflows/build-test-deploy.yaml
  docker-compose.yml
Labels: chore

#168 docs: Translations update from Hosted Weblate
  translations/zh_CN.ts
Labels: documentation

#173 chore: Set min sdk version to 24 (Android 7).
  CMakeLists.txt
Labels: chore

#184 chore: Don't build Qt stuff in bazel cross-compile builds.
  test/BUILD.bazel
Labels: chore

#178 cleanup: Another typo fix, avaliable -> available.
  src/core/core.cpp
  src/core/core.h
  src/persistence/db/upgrades/dbto11.cpp
  src/video/cameradevice.cpp
  src/widget/categorywidget.cpp
  src/widget/chatformheader.cpp
  src/widget/chatformheader.h
  src/widget/form/chatform.cpp
  src/widget/widget.cpp
Labels: cleanup

#174 cleanup: Use tox core "length" functions instead of constants.
  src/core/core.cpp
  src/core/corefile.cpp
  src/persistence/profile.cpp
Labels: cleanup

#190 docs: Add TokTok/qTox adoption to the about form.
  src/net/updatecheck.cpp
  src/net/updatecheck.h
  src/widget/form/settings/aboutform.cpp
  src/widget/form/settings/aboutsettings.ui
  translations/ar.ts
  translations/be.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: documentation

#189 cleanup: Remove now unused DESKTOP_NOTIFICATIONS from cmake preset.
  CMakePresets.json
Labels: cleanup

#183 chore: Point weblate config at the new hosted weblate project.
  .weblate
Labels: chore

#192 fix: Fix use-after-free when closing qTox during a call.
  src/core/coreav.cpp
  util/CMakeLists.txt
  util/include/util/algorithm.h
  util/src/algorithm.cpp
Labels: bug

#122 cleanup: Avoid logging QString as format.
  src/core/core.cpp
  src/core/coreav.cpp
  src/core/corefile.cpp
  src/persistence/settings.cpp
Labels: cleanup

#199 cleanup: Prefix multi-line log messages with the same timestamp.
  src/appmanager.cpp
Labels: cleanup

#198 cleanup: Some random warning cleanups and some typo fixes.
  BUILD.bazel
  audio/BUILD.bazel
  src/BUILD.bazel
  src/chatlog/chatlinecontentproxy.cpp
  src/chatlog/chatlinecontentproxy.h
  src/chatlog/chatwidget.cpp
  src/core/core.cpp
  src/persistence/settings.cpp
  src/widget/categorywidget.cpp
  src/widget/contentdialog.cpp
  src/widget/contentdialogmanager.h
  test/BUILD.bazel
  test/core/fileprogress_test.cpp
  test/model/sessionchatlog_test.cpp
  util/BUILD.bazel
Labels: cleanup

#197 test: Make the invalid proxy test less flaky.
  test/core/core_test.cpp
Labels: test

#202 chore: Use `mkstamp` macro to get git version from bazel build.
  src/BUILD.bazel
Labels: chore

#204 chore: Enable rtti in all builds.
  CMakeLists.txt
Labels: chore

#205 fix: Fix two memory leaks.
  src/widget/contentlayout.cpp
  src/widget/form/debugwidget.cpp
Labels: bug

#206 fix: cmake file dependencies
  cmake/Dependencies.cmake
Labels: bug

#215 cleanup: Stop loading smileypack in a separate thread.
  src/persistence/smileypack.cpp
  src/persistence/smileypack.h
Labels: cleanup

#211 chore: Add arm64 macOS user build.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  src/platform/posixsignalnotifier.cpp
Labels: chore

#214 cleanup: Sort Qt resource files by filename.
  audio/resources/audio_res.qrc
  res.qrc
Labels: cleanup

#193 chore: Add UBSAN option for cmake.
  .ci-scripts/build-qtox-linux.sh
  .ci-scripts/build-qtox-macos.sh
  CMakeLists.txt
  CMakePresets.json
  cmake/CheckAtomic.cmake
  src/nexus.cpp
  test/net/bsu_test.cpp
  test/persistence/paths_test.cpp
Labels: chore

#221 chore: Reduce default number of PR CI builds.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#223 chore: Don't run non-deploy jobs on push (only PR).
  .github/workflows/build-test-deploy.yaml
Labels: chore

#222 cleanup: Reduce repetition in Android build workflow.
  .github/workflows/build-test-deploy.yaml
Labels: cleanup

#224 chore: Fix nightly apk upload.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#219 chore: Add armeabi-v7a build.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  android/6.2.4/AndroidManifest.xml
  android/6.8.1/AndroidManifest.xml
  android/cross-compile/build.sh
  docker-compose.yml
  src/appmanager.cpp
Labels: packaging, chore

#201 chore: Use qt_binary instead of cc_binary for qtox.
  BUILD.bazel
Labels: chore

#213 feat: Add caps-lock indicator in password edit on macOS.
  src/platform/capslock_osx.cpp
  src/widget/passwordedit.cpp
  src/widget/passwordedit.h
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: enhancement

#225 chore: Add ccache to most builds.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#210 cleanup: Use consistent nomenclature for "full screen".
  src/nexus.cpp
  src/nexus.h
  src/widget/conferencewidget.cpp
  src/widget/form/chatform.cpp
  src/widget/widget.cpp
  src/widget/widget.h
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#154 test: Re-enable tests on windows.
  windows/cross-compile/build.sh
Labels: test

#227 chore: Add fully static qtox build.
  .ci-scripts/build-qtox-linux-static.sh
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  cmake/Dependencies.cmake
  docker-compose.yml
  src/main.cpp
Labels: chore

#226 cleanup: Avoid double spaces in logging.
  src/appmanager.cpp
  src/core/core.cpp
  src/core/coreav.cpp
  src/core/corefile.cpp
  src/ipc.cpp
  src/persistence/db/rawdatabase.cpp
  src/persistence/db/upgrades/dbupgrader.cpp
  src/persistence/globalsettingsupgrader.cpp
  src/persistence/personalsettingsupgrader.cpp
  src/persistence/profile.cpp
  src/persistence/settings.cpp
  src/platform/camera/directshow.cpp
  src/video/cameradevice.cpp
  src/widget/form/settings/advancedform.cpp
  src/widget/qrwidget.cpp
  src/widget/widget.cpp
Labels: cleanup

#228 chore: Build windows outputs into arch-specific build dirs.
  windows/cross-compile/build.sh
  windows/cross-compile/check-dlls
Labels: packaging, chore

#229 refactor: Remove the need for `<filesystem>` in logging.
  src/appmanager.cpp
Labels: refactor

#231 fix: Show actual smileys in the smileypack selector.
  src/widget/form/settings/userinterfaceform.cpp
Labels: bug

#235 cleanup: Remove duplicate definition of DECLARE_SIGNAL.
  util/include/util/interface.h
Labels: cleanup

#237 fix: Use the *last* `/src/` to find the source root.
  src/appmanager.cpp
Labels: bug

#241 chore: Don't imgbot-optimise SVGs.
  .imgbotconfig
Labels: chore

#242 docs: Add some more context to the "filing an issue" section.
  CONTRIBUTING.md
Labels: documentation

#243 chore: Fix ccache cache sharing.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#238 perf: Delay debug log loading to show time.
  .dockerignore
  .gitignore
  CMakePresets.json
  src/model/debug/debuglogmodel.cpp
  src/model/debug/debuglogmodel.h
  src/widget/form/debug/debuglog.cpp
  src/widget/form/debug/debuglog.h
Labels: performance

#245 chore: Don't build Debug builds on release tag pushes.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#246 chore: Raise the minor version number on feature releases.
  .github/release-drafter.yml
Labels: chore

#249 cleanup: Reduce amount of implicit casting in signals/slots.
  CMakeLists.txt
  audio/src/backend/openal.cpp
  src/chatlog/content/text.cpp
  src/core/core.cpp
  src/core/core.h
  src/net/updatecheck.cpp
  src/widget/widget.cpp
  src/widget/widget.h
Labels: cleanup

#248 cleanup: Avoid contextless `connect`.
  CMakeLists.txt
  src/core/toxcall.cpp
  src/net/avatarbroadcaster.cpp
  src/nexus.cpp
  src/video/netcamview.cpp
  src/widget/circlewidget.cpp
  src/widget/form/conferenceform.cpp
  src/widget/form/conferenceinviteform.cpp
  src/widget/form/conferenceinvitewidget.cpp
  src/widget/form/debug/debuglog.cpp
  src/widget/form/filesform.cpp
  src/widget/form/settings/aboutform.cpp
  src/widget/friendlistwidget.cpp
  src/widget/friendwidget.cpp
  src/widget/widget.cpp
  test/widget/filesform_test.cpp
Labels: cleanup

#250 chore: Add a CI check to run the macOS distributable binary.
  .ci-scripts/build-qtox-macos.sh
  .github/workflows/build-test-deploy.yaml
  cmake/Installation.cmake
  macos/macfixrpath
Labels: packaging, chore

#247 docs: Translations update from Hosted Weblate
  translations/ru.ts
Labels: documentation

#253 cleanup: Remove unnecessary inheritance of Chatroom.
  CMakeLists.txt
  src/model/chatroom/chatroom.cpp
  src/model/chatroom/chatroom.h
  src/model/chatroom/conferenceroom.h
  src/model/chatroom/friendchatroom.h
Labels: cleanup

#251 docs: Translations update from Hosted Weblate
  translations/es.ts
Labels: documentation

#232 feat: Add many missing emojis from the smiley packs.
  .ci-scripts/build-qtox-linux.sh
  .restyled.yaml
  BUILD.bazel
  CMakeLists.txt
  INSTALL.md
  cmake/Testing.cmake
  smileys/Classic/emoticons.qrc
  smileys/Classic/emoticons.xml
  smileys/EmojiOne/emoticons.qrc
  smileys/EmojiOne/emoticons.xml
  smileys/Universe/emoticons.qrc
  smileys/Universe/emoticons.xml
  smileys/emojione.qrc
  smileys/messaging-emoticon-map.xsd
  smileys/smileys.qrc
  smileys/update_smileys.py
Labels: enhancement

#252 cleanup: Remove duplication of widget IDs.
  src/model/debug/debugobjecttreemodel.cpp
  src/widget/form/chatform.cpp
  src/widget/form/chatform.h
  src/widget/form/genericchatform.h
  src/widget/form/settings/userinterfacesettings.ui
  src/widget/widget.cpp
Labels: cleanup

#230 docs: Add more tooltips to UI settings.
  .gitignore
  src/widget/form/settings/userinterfacesettings.ui
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: documentation

#255 chore: Add static cmake preset.
  CMakePresets.json
Labels: chore

#259 chore: Fix background and icon of macOS dmg.
  .github/workflows/build-test-deploy.yaml
  cmake/Installation.cmake
  macos/Brewfile
  macos/Brewfile-DepBuildDeps
  macos/DS_Store-DMG
  macos/backgroundImage.tiff
  macos/createdmg
  macos/makedist.sh
  macos/welcome.txt
  src/persistence/db/rawdatabase.cpp
Labels: packaging, chore

#258 cleanup: Avoid string concatenation in log output.
  src/core/core.cpp
  src/persistence/settings.cpp
Labels: cleanup

#264 cleanup: Make the tongue emoji `:P` output 😛 instead of 😋.
  smileys/EmojiOne/emoticons.xml
  smileys/Universe/emoticons.xml
Labels: cleanup

#256 refactor: Add logging category to debug log.
  src/appmanager.cpp
  src/model/debug/debuglogmodel.cpp
  src/model/debug/debuglogmodel.h
Labels: refactor

#257 style: Format Objective C++ files with clang-format.
  .clang-format
  src/platform/camera/avfoundation.mm
Labels: style

#266 cleanup: Remove unnecessary path cleaner in tox logger.
  src/core/toxlogger.cpp
Labels: cleanup

#269 chore: Reduce flakiness of macOS builds.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#280 chore: Support toxcore 0.2.19 and below.
  util/src/toxcoreerrorparser.cpp
Labels: chore

#262 cleanup: Remove most uses of `goto`.
  src/persistence/db/rawdatabase.cpp
  src/persistence/db/rawdatabase.h
  src/persistence/profile.cpp
  src/video/cameradevice.cpp
Labels: cleanup

#275 cleanup: Use mutex lockers where possible in video frame handling.
  src/video/videoframe.cpp
  src/video/videoframe.h
Labels: cleanup

#271 chore: Add coverity scan static analysis.
  .github/workflows/coverity-scan.yml
Labels: chore

#274 fix: Don't crash on quit during AV call.
  src/core/toxcall.cpp
  src/core/toxcall.h
Labels: bug

#267 fix: Make camera input work again on macOS.
  audio/src/backend/openal.cpp
  audio/src/backend/openal.h
  macos/info.plist
  src/core/toxcall.cpp
  src/platform/camera/avfoundation.h
  src/platform/camera/avfoundation.mm
  src/video/cameradevice.cpp
  src/video/videomode.cpp
  src/video/videomode.h
  src/widget/form/settings/avform.cpp
Labels: bug

#283 fix: Make sure camera access is gained on macOS before calling.
  src/platform/camera/avfoundation.mm
Labels: bug

#272 cleanup: Ensure message structs don't have uninitialised members.
  src/model/ichatlog.h
  src/model/message.h
  util/include/util/strongtype.h
Labels: cleanup

#284 fix: Disable video device selection box during call.
  src/core/coreav.cpp
  src/core/coreav.h
  src/widget/form/settings/avform.cpp
Labels: bug

#278 fix: Fix occasional deadlock in ending a video call.
  src/video/videoframe.cpp
Labels: bug

#289 chore: Use flatpak dependencies from releases instead of local paths.
  flatpak/io.github.qtox.qTox.json
Labels: chore

#286 cleanup: Remove unused C code.
  src/platform/statusnotifier/closures.c
  src/platform/statusnotifier/closures.h
  src/platform/statusnotifier/enums.c
  src/platform/statusnotifier/enums.h
  src/platform/statusnotifier/interfaces.h
  src/platform/statusnotifier/statusnotifier.c
  src/platform/statusnotifier/statusnotifier.h
Labels: cleanup

#287 chore: Use the same flathub manifest as flathub.
  .github/workflows/build-test-deploy.yaml
  BUILD.bazel
  CMakeLists.txt
  flatpak/io.github.qtox.qTox.json
  flatpak/localize_flathub_descriptor.py
  flatpak/update_flathub_descriptor_dependencies.py
  src/video/videoframe.cpp
Labels: chore

#273 perf: Don't log verbose toxav messages.
  src/appmanager.cpp
Labels: performance

#290 chore: Use ccache in flatpak build.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#279 docs: Update dependency documentation.
  INSTALL.md
Labels: documentation

#292 chore: Add a scheduled workflow to run CI every day.
  .ci-scripts/build-macos-deps.sh
  .ci-scripts/build-macos-qtdeps.sh
  .github/workflows/build-test-deploy.yaml
Labels: chore

#294 chore: Enable ccache in flatpak builds.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  flatpak/build.sh
  flatpak/io.github.qtox.qTox.json
  flatpak/update_flathub_descriptor_dependencies.py
  src/main.cpp
Labels: chore

#276 perf: Improve performance of video frame buffering.
  src/video/videoframe.h
Labels: performance

#302 test: Update loginscreen UI test golden image.
  test/resources/images/loginscreen.png
  test/widget/loginscreen_test.cpp
Labels: test

#305 fix: Don't crash on logout.
  CMakePresets.json
  src/widget/contentlayout.cpp
Labels: bug

#309 cleanup: Fix compilation for Android 7.
  .github/workflows/build-test-deploy.yaml
  src/widget/form/settings/avform.cpp
  util/CMakeLists.txt
  util/include/util/ranges.h
  util/src/ranges.cpp
Labels: cleanup

#308 fix: Don't crash when closing the app after logout.
  src/appmanager.cpp
  src/nexus.cpp
  src/nexus.h
  src/persistence/profile.cpp
  src/persistence/profile.h
Labels: bug

#311 cleanup: Add dep name in the log message file path on macOS.
  .ci-scripts/build-macos-deps.sh
  .ci-scripts/build-macos-qt.sh
  .ci-scripts/macos_install_deps.sh
Labels: cleanup

#315 cleanup: Don't connect to NULL window handle's signals.
  macos/asan.supp
  src/widget/widget.cpp
Labels: cleanup

#316 cleanup: Normalise audio to -1.0 dB.
  audio/README.md
  audio/include/audio/iaudiosink.h
  audio/original/ToxEndCall.wav
  audio/original/ToxIncomingCall.wav
  audio/original/ToxOutgoingCall.wav
  audio/original/call_end.wav
  audio/original/call_incoming.wav
  audio/original/call_outgoing.wav
  audio/original/notification.wav
  audio/resources/ToxEndCall.s16le.pcm
  audio/resources/ToxIncomingCall.s16le.pcm
  audio/resources/ToxOutgoingCall.s16le.pcm
  audio/resources/audio_res.qrc
  audio/resources/call_end.s16le.pcm
  audio/resources/call_incoming.s16le.pcm
  audio/resources/call_outgoing.s16le.pcm
  audio/resources/notification.s16le.pcm
Labels: cleanup

#314 fix: Fix uninitialised read in contact circle widget.
  src/widget/circlewidget.cpp
Labels: bug

#317 cleanup: Add openal logging and audio log category.
  .ci-scripts/build-qtox-linux-static.sh
  CMakeLists.txt
  audio/src/backend/openal.cpp
  cspell.config.yaml
Labels: cleanup

#318 cleanup: Add ffmpeg logging.
  .ci-scripts/build-qtox-linux-static.sh
  cspell.config.yaml
  src/video/camerasource.cpp
  src/video/videoframe.cpp
Labels: cleanup

#319 chore: Install Apple dev certificate for signing macOS distributables.
  .github/scripts/install_apple_cert
  .github/workflows/build-test-deploy.yaml
  cmake/Installation.cmake
  macos/Info.plist
  macos/createdmg
  macos/update-plist-version.sh
Labels: chore

#321 chore: Install homebrew bash v5.
  macos/Brewfile
  macos/Brewfile-DepBuildDeps
  macos/createdmg
  macos/update-plist-version.sh
Labels: chore

#323 cleanup: Don't use deprecated spelling of tox enums.
  .ci-scripts/build-qtox-macos.sh
  src/widget/form/filesform.cpp
Labels: cleanup

#324 chore: Update versions for the 1.18.0-rc.3 release.
  .ci-scripts/build-docs.sh
  .ci-scripts/build-gitstats.sh
  .ci-scripts/build-qtox-linux-static.sh
  .ci-scripts/build-qtox-linux.sh
  .ci-scripts/build-qtox-macos.sh
  .ci-scripts/deploy-docs.sh
  .ci-scripts/deploy-gitstats.sh
  .ci-scripts/lcov.sh
  .ci-scripts/validate-pr.py
  .ci-scripts/verify-commit-format.sh
  .github/workflows/build-test-deploy.yaml
  BUILD.bazel
  MAINTAINING.md
  README.md
  flatpak/update_flathub_descriptor_dependencies.py
  macos/Info.plist
  macos/update-plist-version.sh
  res/io.github.qtox.qTox.appdata.xml
  tools/update-versions.sh
  windows/qtox-nsi-version.sh
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#327 chore: Only run the PR validator on pull requests.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#326 style: Reformat CHANGELOG.md with markdown formatter.
  CHANGELOG.md
Labels: style

#329 chore: Add scripts for uploading and verifying release assets.
  .ci-scripts/import-developer-keys.sh
  .ci-scripts/validate-pr.py
  .github/keys/iphydf.asc
  .github/workflows/build-test-deploy.yaml
  BUILD.bazel
  MAINTAINING.md
  tools/create-tarballs.py
  tools/create-tarballs.sh
  tools/format-code.sh
  tools/lib/PR_bash.source
  tools/sign-release-assets.py
  tools/update-nodes.sh
  tools/update-translation-files.sh
  tools/update-versions.sh
  tools/verify-release-assets.py
Labels: chore

#330 refactor: Move common python code into a library; add RCs to changelog.
  .ci-scripts/validate-pr.py
  .clog.toml
  .github/workflows/build-test-deploy.yaml
  .gitignore
  CHANGELOG.md
  MAINTAINING.md
  flatpak/update_flathub_descriptor_dependencies.py
  tools/create-tarballs.py
  tools/lib/__init__.py
  tools/lib/changelog.py
  tools/lib/git.py
  tools/lib/github.py
  tools/lib/stage.py
  tools/lib/types.py
  tools/sign-release-assets.py
  tools/sync-changelog-tags.py
  tools/update-changelog.py
  tools/validate-pr.py
  tools/verify-release-assets.py
Labels: refactor

#306 feat: add appimage back to ci
  .github/workflows/build-test-deploy.yaml
  appimage/build.sh
  docker-compose.yml
  src/widget/form/genericchatform.cpp
Labels: enhancement

#332 chore: Add script to automate most of the release process.
  .clog.toml
  .github/workflows/build-test-deploy.yaml
  .gitignore
  CHANGELOG.md
  flatpak/io.github.qtox.qTox.json
  flatpak/localize_flathub_descriptor.py
  flatpak/update_flathub_descriptor_dependencies.py
  tools/create-release.py
  tools/lib/changelog.py
  tools/lib/git.py
  tools/lib/github.py
  tools/lib/stage.py
  tools/sync-changelog-tags.py
  tools/update-changelog.py
  tools/validate-pr.py
Labels: chore

#333 chore: Fix appimage release build (`-` instead of `.`).
  .cirrus.yml
  .github/workflows/build-test-deploy.yaml
Labels: chore

#331 chore: Release v1.18.0-rc.4
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#335 fix(Security): Harden the persistence/serialization functions.
  src/persistence/serialize.cpp
  src/persistence/serialize.h
Labels: bug, security

#312 fix: Avoid occasional crash when changing video devices or closing qTox.
  .ci-scripts/macos_install_deps.sh
  .github/workflows/build-test-deploy.yaml
  src/core/coreav.cpp
  src/platform/camera/avfoundation.mm
  src/video/videoframe.cpp
  src/video/videoframe.h
Labels: bug

#322 cleanup: Ensure VideoFrame memory is never leaked.
  .ci-scripts/build-macos-qt.sh
  .ci-scripts/macos_install_deps.sh
  .gitignore
  CMakePresets.json
  macos/run-debug
  src/video/camerasource.cpp
  src/video/corevideosource.cpp
  src/video/videoframe.cpp
  src/video/videoframe.h
Labels: cleanup
