Repository TokTok/qTox, pull requests merged in 2025-02, with the labels that each got.

#487 feat(ci): add CI/CD pipeline, creating rpm package on fedora
  .ci-scripts/package-qtox-linux.sh
  .github/workflows/build-package.yaml
  CMakeLists.txt
  cmake/Package.cmake
  tools/update-versions.sh
Labels: enhancement

#489 fix(video): fix rare deadlock during call cancelation
  src/core/coreav.cpp
  src/core/coreav.h
Labels: bug

#492 docs: Update README to have the correct nightly macOS links.
  .dockerignore
  README.md
Labels: documentation

#488 fix(video): fix the way camera devices are taken, remove warning, when no device is selected
  src/video/cameradevice.cpp
  src/video/cameradevice.h
  src/video/camerasource.cpp
Labels: bug

#490 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#501 docs: Add comment to CLI argument strings to help translators.
  android/cross-compile/build.sh
  appimage/build.sh
  platform/wasm/Dockerfile
  platform/wasm/build.sh
  src/appmanager.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
  windows/cross-compile/build.sh
Labels: documentation

#503 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#500 docs: Add translatable strings
  src/appmanager.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: documentation

#498 cleanup: Remove untranslatable strings from translations.
  src/widget/about/aboutfriendform.cpp
  src/widget/about/aboutfriendform.ui
  test/BUILD.bazel
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#506 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#496 refactor: A bit of cleanup in tox/profile creation/loading.
  src/appmanager.cpp
  src/core/core.cpp
  src/core/core.h
  src/nexus.cpp
  src/nexus.h
  src/persistence/profile.cpp
  src/persistence/profile.h
  src/persistence/settings.cpp
  src/persistence/settings.h
  src/widget/form/settings/advancedform.cpp
  src/widget/widget.cpp
  test/core/core_test.cpp
Labels: refactor

#509 chore: Use ninja build in rpm package job.
  .ci-scripts/package-qtox-linux.sh
  .github/workflows/build-package.yaml
Labels: chore

#508 chore: Add netlify preview build.
  .github/workflows/build-test-deploy.yaml
  .github/workflows/release.yml
  .gitignore
  .netlify/state.json
  platform/wasm/Dockerfile
  platform/wasm/build.sh
  platform/wasm/netlify.sh
Labels: chore

#511 chore: Fix deploy preview.
  .dockerignore
  platform/wasm/build.sh
Labels: chore

#515 fix(chatform): fix the status button alignment
  themes/dark/statusButton/statusButton.qss
  themes/default/statusButton/statusButton.qss
Labels: bug

#520 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#510 cleanup: Move all the platform-specific build stuff to platform/.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  INSTALL.md
  MAINTAINING.md
  cmake/Installation.cmake
  cspell.config.yaml
  platform/android/6.2.4/AndroidManifest.xml
  platform/android/6.8.1/AndroidManifest.xml
  platform/android/cross-compile/build.sh
  platform/android/keystore.jks
  platform/appimage/build.sh
  platform/flatpak/build.sh
  platform/flatpak/io.github.qtox.qTox.json
  platform/flatpak/localize_flathub_descriptor.py
  platform/flatpak/update_flathub_descriptor_dependencies.py
  platform/macos/BUILD.bazel
  platform/macos/Brewfile
  platform/macos/Brewfile-DepBuildDeps
  platform/macos/Info.plist
  platform/macos/asan.supp
  platform/macos/backgroundImage.tiff
  platform/macos/createdmg
  platform/macos/gplv3.rtf
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/Contents.json
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-128.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-128@2x.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-16.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-16@2x.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-256.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-256@2x.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-32.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-32@2x.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-512.png
  platform/macos/qtox.icns.xcassets/qtox.icns.appiconset/qtox.icns-512@2x.png
  platform/macos/run-debug
  platform/macos/update-plist-version.sh
  platform/windows/BUILD.bazel
  platform/windows/cross-compile/README.md
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/check-dlls
  platform/windows/generate-icon.sh
  platform/windows/qtox-nsi-version.sh
  platform/windows/qtox.ico
  platform/windows/qtox.nsi
  platform/windows/qtox.rc
  platform/windows/qtox64.nsi
  tools/validate_pr.py
  windows/qtox.rc
Labels: cleanup

#527 fix(About): Retranslate the important message when changing language.
  src/widget/form/settings/advancedform.cpp
  src/widget/form/settings/advancedform.h
Labels: bug

#522 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#532 chore: Update nodes.json.
  res/nodes.json
Labels: chore

#518 cleanup: Rename "Add new circle" to "Create new circle".
  src/widget/friendlistwidget.cpp
  src/widget/friendlistwidget.h
  src/widget/widget.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#536 docs: Allow translation of "min" in Auto away settings.
  src/widget/form/settings/generalsettings.ui
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: documentation

#534 docs: Clarify to translators what the LTR string should be.
  src/widget/translator.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: documentation

#528 chore: Use reusable deploy workflows.
  .ci-scripts/build-local-deps.sh
  .ci-scripts/build-local-qt.sh
  .ci-scripts/build-qtox-macos.sh
  .ci-scripts/local_install_deps.sh
  .github/workflows/build-test-deploy.yaml
  .github/workflows/draft.yml
  CMakeLists.txt
  cmake/Installation.cmake
  cmake/Testing.cmake
  platform/android/cross-compile/build.sh
  platform/android/qt-6.2.4/AndroidManifest.xml
  platform/android/qt-6.8.1/AndroidManifest.xml
  platform/appimage/build.sh
  platform/deps.depfile
  platform/flatpak/build.sh
  platform/linux/io.github.qtox.qTox.appdata.xml
  platform/linux/io.github.qtox.qTox.desktop
  platform/macos/Brewfile-static
  platform/macos/build.sh
  platform/macos/createdmg
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/dll-deps
  platform/windows/generate-icon.sh
  platform/windows/qtox.ico
  platform/windows/qtox.nsi
  tools/update-versions.sh
  tools/validate_pr.py
Labels: packaging, chore

#541 docs: Update changelog to new format requirements.
  CHANGELOG.md
Labels: documentation

#544 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#537 chore: Move release related tools to ci-tools.
  .github/workflows/build-test-deploy.yaml
  platform/flatpak/update_flathub_descriptor_dependencies.py
  platform/wasm/build.sh
  tools/create_release.py
  tools/create_tarballs.py
  tools/lib/__init__.py
  tools/lib/changelog.py
  tools/lib/git.py
  tools/lib/github.py
  tools/lib/stage.py
  tools/lib/types.py
  tools/sign_release_assets.py
  tools/translate.py
  tools/update_changelog.py
  tools/update_nodes.py
  tools/validate_pr.py
  tools/verify_release_assets.py
Labels: chore

#542 chore: Unify windows builder script with ci-tools.
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/dll-deps
Labels: chore

#545 cleanup: Use ci-tools scripts instead of local copies.
  .github/workflows/build-test-deploy.yaml
  cmake/Installation.cmake
  platform/android/cross-compile/build.sh
  platform/android/keystore.jks
  platform/appimage/build.sh
  platform/flatpak/build.sh
  platform/macos/build.sh
  platform/macos/createdmg
  platform/macos/gplv3.rtf
  platform/windows/cross-compile/README.md
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/check-dlls
  platform/windows/generate-icon.sh
  resources/images/icons/qtox.icns
  resources/images/icons/qtox_profile.icns
Labels: cleanup

#543 chore: Unify android builder script with ci-tools.
  .github/workflows/build-test-deploy.yaml
  cmake/Installation.cmake
  platform/android/cross-compile/build.sh
  platform/android/keystore.jks
  platform/appimage/build.sh
  platform/flatpak/build.sh
  platform/macos/build.sh
  platform/macos/createdmg
  platform/macos/gplv3.rtf
  platform/windows/cross-compile/README.md
  platform/windows/cross-compile/build.sh
  platform/windows/cross-compile/check-dlls
  platform/windows/generate-icon.sh
  resources/images/icons/qtox.icns
  resources/images/icons/qtox_profile.icns
Labels: chore

#538 chore: Add release issue template and workflow.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/release.yml
  .github/workflows/build-package.yml
  .github/workflows/build-test-deploy.yml
  .github/workflows/release.yml
  .reviewable/completion.js
  .reviewable/settings.yaml
Labels: chore

#535 docs: Add groupbot and NGC chat to the readme.
  README.md
Labels: documentation

#539 chore: Add CMakeLists.txt version updater.
  tools/update-versions.sh
Labels: chore

#552 chore: Fix version updater script.
  cmake/Package.cmake
  tools/update-versions.sh
Labels: chore

#540 docs: Update readme to no longer say we're unofficial.
  README.md
Labels: documentation

#553 chore: Release v1.18.3-rc.1
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/Package.cmake
  platform/linux/io.github.qtox.qTox.appdata.xml
  platform/macos/Info.plist
  platform/windows/qtox64.nsi
Labels: chore

#554 docs: Fix macOS screenshot in readme.
  README.md
Labels: documentation

#556 fix: Use correct bug template in report bug button.
  src/widget/form/settings/aboutform.cpp
Labels: bug

#557 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#559 chore: Release v1.18.3
  CHANGELOG.md
  README.md
  platform/linux/io.github.qtox.qTox.appdata.xml
  platform/macos/Info.plist
  platform/windows/qtox64.nsi
Labels: chore
