Repository TokTok/qTox, pull requests merged in 2025-01, with the labels that each got.

#340 chore: Add test workflows for appimage/flatpak binaries.
  .cirrus.yml
  .github/workflows/build-test-deploy.yaml
Labels: chore

#339 cleanup: Use version.h in cmake build as well.
  cmake/Dependencies.cmake
  src/appmanager.cpp
  src/net/updatecheck.cpp
  src/version.h.in
  src/widget/form/settings/aboutform.cpp
Labels: cleanup

#336 test: Add a fuzz test for the remaining 2 serialize functions.
  src/BUILD.bazel
  test/BUILD.bazel
  test/persistence/serialize_fuzz_test.cpp
Labels: test

#334 chore: Extend the release script to the post-merge steps.
  .clog.toml
  .github/workflows/build-test-deploy.yaml
  .github/workflows/coverity-scan.yml
  CHANGELOG.md
  MAINTAINING.md
  macos/createdmg
  tools/create-release.py
  tools/create_release.py
  tools/create_tarballs.py
  tools/lib/git.py
  tools/lib/github.py
  tools/lib/stage.py
  tools/sign_release_assets.py
  tools/update_changelog.py
  tools/validate_pr.py
  tools/verify_release_assets.py
Labels: chore

#342 chore: Allow workflow dispatch to trigger _all_ jobs.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#338 chore: Release v1.18.0
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#337 perf(Video): Avoid copying frame buffers unnecessarily.
  src/core/coreav.cpp
  src/video/videoframe.cpp
  src/video/videoframe.h
Labels: performance

#344 chore: Some more fixes to the releaser script.
  tools/create_release.py
  tools/lib/github.py
Labels: chore

#345 cleanup: Remove unnecessary space at the end of a warning message.
  src/widget/form/chatform.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/no_nb.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#90 cleanup: Use emplace_back instead of push_back.
  src/chatlog/chatwidget.cpp
  src/persistence/db/upgrades/dbto11.cpp
  src/persistence/db/upgrades/dbupgrader.cpp
Labels: cleanup

#261 feat(UI): Better integration with system dark modes.
  .clang-tidy
  src/persistence/settings.cpp
  src/widget/style.cpp
  src/widget/style.h
Labels: enhancement

#91 cleanup: Use `true`/`false` instead of `0`/`1` for boolean literals.
  .clang-tidy
  src/core/toxfile.h
  src/model/conference.cpp
  src/model/exiftransform.cpp
Labels: cleanup

#343 feat(Languages): Fully translate every supported language.
  .github/workflows/build-test-deploy.yaml
  src/widget/form/settings/generalform.cpp
  tools/lib/stage.py
  tools/translate.py
  translations/CMakeLists.txt
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/i18n.pri
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/pl.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/translations.qrc
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_TW.ts
Labels: enhancement

#356 test: Check that the version on release is considered stable.
  .ci-scripts/build-docs.sh
  .ci-scripts/create-identity.sh
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  appimage/build.sh
  cmake/Dependencies.cmake
  src/appmanager.cpp
  src/net/updatecheck.cpp
  src/net/updatecheck.h
  src/version.cpp.in
  src/version.h
  src/version.h.in
  src/widget/form/settings/aboutform.cpp
  test/BUILD.bazel
  windows/cross-compile/build.sh
Labels: test

#357 chore: Only run the release asset verification script once a day.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#347 feat(Login): Add a tooltip and WhatsThis for the password field.
  src/loginscreen.ui
  tools/translate.py
  tools/translate_ai.py
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: enhancement

#359 chore: Fixes to the releaser script.
  .github/workflows/build-test-deploy.yaml
  tools/create_release.py
  tools/lib/git.py
  tools/lib/github.py
Labels: chore

#360 chore: Cache flatpak's ccache separately (and upgrade to KDE 6.8).
  .github/workflows/build-test-deploy.yaml
  flatpak/io.github.qtox.qTox.json
Labels: chore

#365 chore: Fix version.cpp generation in bazel build.
  src/BUILD.bazel
Labels: chore

#358 chore: Post warning message when we should release soon.
  .github/workflows/release.yml
Labels: chore

#361 chore: Release v1.18.1-rc.1
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#368 chore: Fix releaser to support checking the current latest release.
  .github/workflows/build-test-deploy.yaml
  tools/create_release.py
  tools/lib/github.py
Labels: chore

#369 cleanup: Fix mypy errors in Python code.
  .ci-scripts/version-regex.sh
  tools/lib/github.py
  tools/translate.py
  tools/translate_ai.py
Labels: cleanup

#373 chore: Reinstate bazel build.
  .cirrus.yml
Labels: chore

#370 feat: Add a command line option to run the update-check.
  src/appmanager.cpp
  src/appmanager.h
  src/net/updatecheck.cpp
  src/net/updatecheck.h
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: enhancement

#372 cleanup: Don't translate command line flags.
  src/appmanager.cpp
  src/widget/form/settings/advancedsettings.ui
  tools/translate.py
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#377 chore: Add update-check to the CI smoke test.
  .ci-scripts/smoke-test.sh
  .github/workflows/build-test-deploy.yaml
Labels: chore

#379 fix: Audio notifications are no longer cut off.
  audio/original/call_end.wav
  audio/original/call_incoming.wav
  audio/original/call_outgoing.wav
  audio/original/notification.wav
  audio/resources/call_end.s16le.pcm
  audio/resources/call_incoming.s16le.pcm
  audio/resources/call_outgoing.s16le.pcm
  audio/resources/notification.s16le.pcm
Labels: bug

#376 cleanup: Minor clarifications on command line errors.
  src/appmanager.cpp
  src/persistence/settings.cpp
Labels: cleanup

#383 chore: Release v1.18.1-rc.3
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#384 chore: Don't consider an untagged build to be stable.
  .ci-scripts/smoke-test.sh
  tools/create_release.py
Labels: chore

#385 chore: Release v1.18.1
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#390 fix(Chat): Correctly display newlines in incoming chat messages.
  src/core/toxstring.cpp
  test/core/toxstring_test.cpp
Labels: bug

#388 fix(UI): Message edit context menu now changes colour to hover/selection
  res.qrc
  src/widget/form/genericchatform.cpp
  themes/dark/genericChatForm/genericChatForm.qss
  themes/default/genericChatForm/genericChatForm.qss
Labels: bug

#175 cleanup: Make ToxId move-only.
  src/core/toxid.cpp
  src/core/toxid.h
  src/widget/form/addfriendform.cpp
  test/core/toxid_test.cpp
Labels: cleanup

#391 chore: Reuse macOS local deps scripts for Linux.
  .ci-scripts/build-local-deps.sh
  .ci-scripts/build-local-qt.sh
  .ci-scripts/local_install_deps.sh
  .ci-scripts/macos_install_deps.sh
  .github/workflows/build-test-deploy.yaml
  CMakePresets.json
  cmake/Dependencies.cmake
Labels: chore

#392 cleanup: ToxId needs to be copyable for Qt to pass it through signals.
  .ci-scripts/build-qtox-macos.sh
  .github/workflows/build-test-deploy.yaml
  INSTALL.md
  src/core/toxid.cpp
  src/core/toxid.h
  test/core/toxid_test.cpp
Labels: cleanup

#395 docs: Add nightly built screenshot to readme.
  .github/workflows/build-test-deploy.yaml
  README.md
Labels: documentation

#398 chore: Fix macOS screenshot taking.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#397 chore: Speed up clang-tidy by not compiling code.
  .ci-scripts/build-qtox-linux.sh
Labels: chore

#393 feat(Pictures): Add QOI image format support.
  .ci-scripts/build-local-deps.sh
  CMakeLists.txt
  cmake/Dependencies.cmake
  src/main.cpp
  src/widget/imagepreviewwidget.cpp
Labels: enhancement

#402 chore: Fix AppImage build.
  appimage/build.sh
  cmake/Dependencies.cmake
Labels: chore

#396 cleanup: Make it harder to forget to close settings groups.
  src/persistence/settings.cpp
Labels: cleanup

#78 cleanup: Use `.empty()` instead of `.size() == 0`.
  .clang-tidy
  audio/src/backend/openal.cpp
  src/chatlog/chatline.cpp
  src/chatlog/chatwidget.cpp
  src/core/toxfileprogress.cpp
  src/model/notificationgenerator.cpp
  src/video/videoframe.cpp
  test/model/friendmessagedispatcher_test.cpp
  test/net/bsu_test.cpp
Labels: cleanup

#89 cleanup: Use range-for in more places.
  .clang-tidy
  src/chatlog/chatline.cpp
  src/ipc.cpp
  src/model/friendlist/friendlistmanager.cpp
  src/net/bootstrapnodeupdater.cpp
  src/widget/form/settings/avform.cpp
  src/widget/friendlistwidget.cpp
  test/model/friendlistmanager_test.cpp
Labels: cleanup

#401 test: Add fuzzer for kimageformats.
  test/BUILD.bazel
  test/chatlog/qimage_fuzz_test.cpp
Labels: test

#82 cleanup: Return braced initialiser list where possible.
  .clang-tidy
  src/chatlog/chatlinecontent.cpp
  src/chatlog/chatmessage.cpp
  src/chatlog/chatwidget.cpp
  src/chatlog/content/broken.cpp
  src/chatlog/content/image.cpp
  src/chatlog/content/notificationicon.cpp
  src/chatlog/content/spinner.cpp
  src/chatlog/content/text.cpp
  src/chatlog/content/timestamp.cpp
  src/core/chatid.cpp
  src/core/core.cpp
  src/model/chatlogitem.cpp
  src/model/conference.cpp
  src/model/debug/debuglogmodel.cpp
  src/model/debug/debugobjecttreemodel.cpp
  src/persistence/history.cpp
  src/persistence/profilelocker.cpp
  src/persistence/settings.cpp
  src/platform/camera/v4l2.cpp
  src/video/videomode.cpp
  src/widget/form/filesform.cpp
  src/widget/form/genericchatform.cpp
  src/widget/imagepreviewwidget.cpp
  src/widget/searchform.cpp
  src/widget/tool/croppinglabel.cpp
  src/widget/tool/screengrabberchooserrectitem.cpp
  src/widget/widget.cpp
  test/mock/include/mock/mockcoreidhandler.h
  test/mock/include/mock/mockcoresettings.h
Labels: cleanup

#405 cleanup: Use fewer image formats on Windows.
  windows/cross-compile/build.sh
Labels: cleanup

#86 cleanup: Reduce nesting of `else` clauses after `return`.
  .ci-scripts/build-qtox-linux.sh
  .clang-tidy
  src/chatlog/chatwidget.cpp
  src/core/core.cpp
  src/core/coreav.cpp
  src/core/toxid.cpp
  src/core/toxpk.cpp
  src/friendlist.cpp
  src/ipc.cpp
  src/model/chathistory.cpp
  src/model/notificationgenerator.cpp
  src/model/status.cpp
  src/net/bootstrapnodeupdater.cpp
  src/nexus.cpp
  src/persistence/db/rawdatabase.cpp
  src/persistence/db/upgrades/dbupgrader.cpp
  src/persistence/history.cpp
  src/persistence/profilelocker.cpp
  src/persistence/settingsserializer.cpp
  src/platform/autorun_xdg.cpp
  src/video/videoframe.cpp
  src/widget/categorywidget.cpp
  src/widget/conferencewidget.cpp
  src/widget/flowlayout.cpp
  src/widget/form/genericchatform.cpp
  src/widget/friendlistwidget.cpp
  src/widget/imagepreviewwidget.cpp
  src/widget/notificationscrollarea.cpp
  src/widget/style.cpp
  src/widget/tool/messageboxmanager.cpp
  src/widget/widget.cpp
Labels: cleanup

#409 cleanup: We don't compile C sources in qTox.
  CMakeLists.txt
  CMakePresets.json
  cmake/Dependencies.cmake
Labels: cleanup

#380 cleanup: Give AI more context for translations.
  tools/translate_ai.py
Labels: cleanup

#415 fix(Security): Fix heap buffer overflow in receiving pictures.
  src/BUILD.bazel
  src/model/exiftransform.cpp
  test/BUILD.bazel
  test/model/exiftransform_fuzz_test.cpp
  test/model/exiftransform_test.cpp
Labels: bug

#417 fix(tools): Use tag strings in release tarballs.
  tools/create_tarballs.py
Labels: bug

#413 refactor: Hide database implementation behind an interface.
  CMakeLists.txt
  src/BUILD.bazel
  src/persistence/db/rawdatabase.cpp
  src/persistence/db/rawdatabase.h
  src/persistence/db/rawdatabaseimpl.cpp
  src/persistence/db/rawdatabaseimpl.h
  src/persistence/profile.cpp
  test/persistence/dbschema_test.cpp
  test/persistence/dbupgrade/dbTo11_test.cpp
Labels: refactor

#263 refactor: Make database query objects move-only.
  src/persistence/db/rawdatabase.h
  src/persistence/db/rawdatabaseimpl.cpp
  src/persistence/db/rawdatabaseimpl.h
  src/persistence/db/upgrades/dbto11.cpp
  src/persistence/db/upgrades/dbto11.h
  src/persistence/db/upgrades/dbupgrader.cpp
  src/persistence/db/upgrades/dbupgrader.h
  src/persistence/history.cpp
  src/persistence/history.h
  test/dbutility/include/dbutility/dbutility.h
  test/dbutility/src/dbutility.cpp
  test/persistence/dbschema_test.cpp
  test/persistence/dbupgrade/dbTo11_test.cpp
Labels: refactor

#420 cleanup: Remove useless translation strings.
  src/chatlog/content/filetransferwidget.ui
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#76 cleanup: Use `make_unique` and `make_shared` instead of `new`.
  .clang-tidy
  src/appmanager.cpp
  src/chatlog/chatmessage.cpp
  src/chatlog/content/filetransferwidget.cpp
  src/chatlog/content/spinner.cpp
  src/core/coreav.cpp
  src/ipc.cpp
  src/persistence/profile.cpp
  src/platform/camera/v4l2.cpp
  src/platform/posixsignalnotifier.cpp
  src/widget/chatformheader.cpp
  src/widget/emoticonswidget.cpp
  src/widget/form/chatform.cpp
  src/widget/form/settingswidget.cpp
  src/widget/qrwidget.cpp
  src/widget/tool/callconfirmwidget.cpp
  src/widget/widget.cpp
  test/model/friendlistmanager_test.cpp
  test/persistence/dbschema_test.cpp
  test/persistence/dbupgrade/dbTo11_test.cpp
  test/platform/posixsignalnotifier_test.cpp
  test/widget/filesform_test.cpp
Labels: cleanup

#418 test: Add a login screen test for profile creation.
  src/nexus.cpp
  src/widget/loginscreen.cpp
  src/widget/loginscreen.h
  src/widget/tool/messageboxmanager.cpp
  test/resources/images/loginscreen_empty.png
  test/resources/images/loginscreen_ok.png
  test/resources/test_data.qrc
  test/widget/loginscreen_test.cpp
  translations/pr.ts
Labels: test

#421 cleanup: Add missing test deps.
  test/BUILD.bazel
Labels: cleanup

#425 cleanup: Fix some more clang-tidy warnings.
  src/model/notificationgenerator.cpp
  src/nexus.cpp
  src/platform/camera/avfoundation.mm
  src/platform/desktop_notifications/desktopnotifybackend_dbus.cpp
  test/model/conferencemessagedispatcher_test.cpp
  test/model/friendmessagedispatcher_test.cpp
  test/model/notificationgenerator_test.cpp
  test/model/sessionchatlog_test.cpp
  test/persistence/dbupgrade/dbTo11_test.cpp
Labels: cleanup

#423 fix: cmake POSITION_INDEPENDENT_CODE global setting
  CMakeLists.txt
Labels: bug

#422 chore: Speed up clang-tidy run using clangd.
  .ci-scripts/build-qtox-linux.sh
  .clang-tidy
  .github/workflows/build-test-deploy.yaml
  .gitignore
  cspell.config.yaml
  tools/lsp_tidy.py
Labels: chore

#429 chore: Release v1.18.2-rc.1
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#428 cleanup: Add some logging for reasons why notifications might fail.
  src/platform/desktop_notifications/desktopnotify.cpp
Labels: cleanup

#434 chore: Release v1.18.2
  CHANGELOG.md
  README.md
  macos/Info.plist
  res/io.github.qtox.qTox.appdata.xml
  windows/qtox.nsi
  windows/qtox64.nsi
Labels: chore

#435 chore: Fix releaser to properly wait for builds.
  tools/create_release.py
  tools/lib/github.py
Labels: chore

#438 docs: Translations update from Hosted Weblate
  translations/ja.ts
Labels: documentation

#80 cleanup: Pass moved-from objects by value instead of const ref.
  .clang-tidy
  src/chatlog/chatlinestorage.cpp
  src/chatlog/chatlinestorage.h
  src/chatlog/content/text.cpp
  src/chatlog/content/text.h
  src/core/coreav.cpp
  src/core/toxfile.cpp
  src/core/toxoptions.cpp
  src/core/toxoptions.h
  src/core/toxpk.cpp
  src/core/toxpk.h
  src/core/toxstring.cpp
  src/core/toxstring.h
  src/model/chatlogitem.cpp
  src/model/chatlogitem.h
  src/model/conference.cpp
  src/model/conference.h
  src/model/conferenceinvite.cpp
  src/model/conferenceinvite.h
  src/model/friend.cpp
  src/model/friend.h
  src/persistence/db/rawdatabase.h
  src/persistence/db/rawdatabaseimpl.cpp
  src/persistence/db/rawdatabaseimpl.h
  src/persistence/db/upgrades/dbupgrader.cpp
  src/persistence/db/upgrades/dbupgrader.h
  src/persistence/history.cpp
  src/persistence/history.h
  src/persistence/profile.cpp
  src/persistence/profile.h
  src/persistence/settings.h
  src/persistence/settingsserializer.cpp
  src/persistence/settingsserializer.h
  src/persistence/smileypack.cpp
  src/platform/camera/v4l2.cpp
  src/video/cameradevice.cpp
  src/video/cameradevice.h
  src/video/netcamview.cpp
  src/video/videosurface.cpp
  src/video/videosurface.h
  src/widget/form/conferenceinvitewidget.cpp
  src/widget/form/conferenceinvitewidget.h
  src/widget/form/settings/aboutform.cpp
  src/widget/form/settings/avform.cpp
  src/widget/form/settings/genericsettings.cpp
  src/widget/form/settings/genericsettings.h
  src/widget/form/tabcompleter.h
  src/widget/friendwidget.cpp
  src/widget/maskablepixmapwidget.cpp
  src/widget/notificationscrollarea.cpp
  test/chatlog/chatlinestorage_test.cpp
  test/model/friendlistmanager_test.cpp
  test/model/friendmessagedispatcher_test.cpp
  tools/lsp_tidy.py
Labels: cleanup

#439 cleanup: Use explicit constructors where possible.
  .clang-tidy
  audio/include/audio/iaudiosink.h
  audio/include/audio/iaudiosource.h
  audio/src/backend/alsink.h
  audio/src/backend/alsource.h
  src/core/core.cpp
  src/core/toxfileprogress.h
  src/core/toxoptions.cpp
  src/core/toxoptions.h
  src/model/chatlogitem.h
  src/model/message.h
  src/model/sessionchatlog.cpp
  src/net/avatarbroadcaster.h
  src/persistence/db/rawdatabase.h
  src/persistence/db/rawdatabaseimpl.cpp
  src/persistence/history.cpp
  src/persistence/history.h
  src/persistence/paths.h
  src/persistence/settings.h
  src/persistence/settingsserializer.h
  src/video/videosurface.h
  src/widget/form/filetransferlist.h
  src/widget/imagepreviewwidget.h
  src/widget/searchform.h
  src/widget/tool/activatedialog.h
  src/widget/tool/identicon.h
  test/model/friendlistmanager_test.cpp
Labels: cleanup

#83 cleanup: Make member functions `const` where possible.
  .clang-tidy
  src/model/debug/debugobjecttreemodel.cpp
  src/model/friendlist/friendlistmanager.cpp
  src/model/friendlist/friendlistmanager.h
  src/video/scopedavdictionary.cpp
  src/video/scopedavdictionary.h
  src/widget/contentlayout.cpp
  src/widget/contentlayout.h
  src/widget/form/chatform.cpp
  src/widget/form/chatform.h
  src/widget/form/settings/avform.cpp
  src/widget/form/settings/avform.h
  src/widget/genericchatroomwidget.cpp
  src/widget/genericchatroomwidget.h
  src/widget/searchtypes.h
  src/widget/tool/removechatdialog.h
  src/widget/tool/screenshotgrabber.cpp
  src/widget/tool/screenshotgrabber.h
  src/widget/widget.cpp
  src/widget/widget.h
  test/model/friendlistmanager_test.cpp
  test/persistence/dbschema_test.cpp
Labels: cleanup

#79 cleanup: Don't move trivially copyable values.
  .clang-tidy
  src/core/chatid.cpp
  src/core/chatid.h
  src/core/toxpk.cpp
  src/core/toxpk.h
  src/model/chathistory.cpp
  src/model/friendmessagedispatcher.cpp
  src/model/ichatlog.h
  src/model/message.h
  src/model/sessionchatlog.cpp
  src/model/sessionchatlog.h
  src/persistence/db/upgrades/dbupgrader.cpp
  src/platform/camera/v4l2.cpp
  src/widget/widget.cpp
  test/core/chatid_test.cpp
  test/model/sessionchatlog_test.cpp
Labels: cleanup

#440 fix(Clipboard): Improve "copy link to clipboard" on Linux.
  src/widget/form/genericchatform.cpp
Labels: bug

#442 feat(Debug): Add stack trace logging on crash.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  cmake/Dependencies.cmake
  cmake/Testing.cmake
  src/BUILD.bazel
  src/platform/posixsignalnotifier.cpp
  src/platform/stacktrace.cpp
  src/platform/stacktrace.h
  test/BUILD.bazel
  test/platform/stacktrace_test.cpp
Labels: enhancement

#441 feat(Groups): Add a "copy peer ID" context menu action in conferences.
  src/widget/form/conferenceform.cpp
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: enhancement

#446 test: Get better error messages in notification test.
  test/model/notificationgenerator_test.cpp
Labels: test

#85 cleanup: Avoid multiple declarations per statement.
  .clang-tidy
  audio/src/backend/openal.cpp
  src/appmanager.cpp
  src/core/corefile.cpp
  src/persistence/profile.cpp
  src/platform/timer_x11.cpp
  src/widget/flowlayout.cpp
  src/widget/genericchatitemlayout.cpp
  src/widget/qrwidget.cpp
  src/widget/tool/callconfirmwidget.cpp
  src/widget/tool/movablewidget.cpp
  test/model/exiftransform_test.cpp
Labels: cleanup

#448 cleanup: Add support for macOS before 12.0.
  src/platform/capslock_osx.cpp
  src/platform/timer_osx.cpp
  src/widget/translator.cpp
  src/widget/translator.h
Labels: cleanup

#450 cleanup: Use braces initialiser for io_service_t.
  src/platform/capslock_osx.cpp
  src/platform/timer_osx.cpp
Labels: cleanup

#451 chore: Add a macos-10.15 build.
  .ci-scripts/build-qtox-macos.sh
  .ci-scripts/local_install_deps.sh
  .github/workflows/build-test-deploy.yaml
  src/platform/capslock_osx.cpp
  src/platform/timer_osx.cpp
Labels: chore

#452 feat(About): Show update available in nightly builds.
  src/net/updatecheck.cpp
  src/widget/form/settings/aboutform.cpp
Labels: enhancement

#456 chore: Move toktok-stack test to circleci.
  .circleci/bazel-test
  .circleci/config.yml
  .cirrus.yml
  cmake/Dependencies.cmake
Labels: chore

#454 cleanup: Remove useless translation.
  .circleci/bazel-test
  .circleci/config.yml
  src/widget/form/searchsettingsform.ui
  translations/ar.ts
  translations/be.ts
  translations/ber.ts
  translations/bg.ts
  translations/bn.ts
  translations/cs.ts
  translations/da.ts
  translations/de.ts
  translations/el.ts
  translations/eo.ts
  translations/es.ts
  translations/et.ts
  translations/fa.ts
  translations/fi.ts
  translations/fr.ts
  translations/gl.ts
  translations/he.ts
  translations/hr.ts
  translations/hu.ts
  translations/is.ts
  translations/it.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lt.ts
  translations/lv.ts
  translations/mk.ts
  translations/nb_NO.ts
  translations/nl.ts
  translations/nl_BE.ts
  translations/pl.ts
  translations/pr.ts
  translations/pt.ts
  translations/pt_BR.ts
  translations/ro.ts
  translations/ru.ts
  translations/si.ts
  translations/sk.ts
  translations/sl.ts
  translations/sq.ts
  translations/sr.ts
  translations/sr_Latn.ts
  translations/sv.ts
  translations/sw.ts
  translations/ta.ts
  translations/tr.ts
  translations/ug.ts
  translations/uk.ts
  translations/ur.ts
  translations/vi.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#464 chore: Add emojis to the issue templates.
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: chore

#444 docs: Translations update from Hosted Weblate
  translations/fi.ts
Labels: documentation

#88 cleanup: Use raw strings to simplify regexes.
  .clang-tidy
  src/model/message.cpp
  src/widget/form/tabcompleter.cpp
  src/widget/tool/croppinglabel.cpp
Labels: cleanup

#465 chore: Add issue type to the issue templates.
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: chore

#466 cleanup: Mark some more variables as `const`.
  .ci-scripts/build-qtox-linux.sh
  .cirrus.yml
  src/persistence/profile.cpp
  src/widget/widget.cpp
  test/dbutility/src/dbutility.cpp
Labels: cleanup

#84 cleanup: Simplify boolean returns.
  src/chatlog/content/text.cpp
  src/core/core.cpp
  src/core/coreav.cpp
  src/model/friendlist/friendlistmanager.cpp
  src/persistence/paths.cpp
Labels: cleanup

#480 feat(Web): Preliminary support for running qTox in the browser.
  .github/workflows/build-test-deploy.yaml
  CMakeLists.txt
  audio/src/backend/openal.cpp
  cmake/Dependencies.cmake
  docker-compose.yml
  platform/wasm/build.sh
  src/appmanager.cpp
  src/core/toxlogger.cpp
  src/ipc.cpp
  src/ipc.h
  src/main.cpp
  src/persistence/profilelocker.cpp
  src/platform/posixsignalnotifier.cpp
Labels: enhancement

#481 chore: Deploy webqtox to Netlify.
  .github/workflows/build-test-deploy.yaml
  netlify.toml
Labels: chore

#483 chore: Fix netlify deploy.
  .github/workflows/build-test-deploy.yaml
Labels: chore

#478 fix(chatform): Remove assertion that breaks friend information call.
  src/persistence/history.cpp
Labels: bug

#485 chore: Fix netlify headers so webqtox can work.
  .github/workflows/build-test-deploy.yaml
  netlify.toml
  platform/wasm/_headers
Labels: chore

#484 chore: Add a wasm run dockerfile.
  .dockerignore
  .github/workflows/build-test-deploy.yaml
  platform/wasm/Dockerfile
  platform/wasm/run.sh
Labels: chore

#472 cleanup: Enable some more modernize clang-tidy checks.
  .clang-tidy
  audio/src/backend/openal.cpp
  src/appmanager.cpp
  src/chatlog/chatlinestorage.cpp
  src/chatlog/chatwidget.cpp
  src/conferencelist.cpp
  src/core/core.cpp
  src/core/coreav.cpp
  src/friendlist.cpp
  src/model/debug/debugobjecttreemodel.cpp
  src/net/bootstrapnodeupdater.cpp
  src/net/toxuri.cpp
  src/persistence/profile.cpp
  src/persistence/profilelocker.cpp
  src/persistence/settings.cpp
  src/persistence/settingsserializer.cpp
  src/platform/desktop_notifications/desktopnotifybackend_dbus.cpp
  src/platform/x11_display.h
  src/video/camerasource.cpp
  src/video/netcamview.cpp
  src/widget/categorywidget.cpp
  src/widget/chatformheader.cpp
  src/widget/circlewidget.cpp
  src/widget/conferencewidget.cpp
  src/widget/contentdialog.cpp
  src/widget/contentdialogmanager.cpp
  src/widget/emoticonswidget.cpp
  src/widget/flowlayout.cpp
  src/widget/form/addfriendform.cpp
  src/widget/form/chatform.cpp
  src/widget/form/conferenceform.cpp
  src/widget/form/conferenceinviteform.cpp
  src/widget/form/genericchatform.cpp
  src/widget/form/profileform.cpp
  src/widget/form/setpassworddialog.cpp
  src/widget/form/settings/advancedform.cpp
  src/widget/form/settings/avform.cpp
  src/widget/form/settings/userinterfaceform.cpp
  src/widget/form/settingswidget.cpp
  src/widget/form/settingswidget.h
  src/widget/friendlistlayout.cpp
  src/widget/friendlistwidget.cpp
  src/widget/friendwidget.cpp
  src/widget/genericchatitemlayout.cpp
  src/widget/notificationedgewidget.cpp
  src/widget/searchform.cpp
  src/widget/tool/callconfirmwidget.cpp
  src/widget/tool/identicon.cpp
  src/widget/tool/movablewidget.cpp
  src/widget/tool/screengrabberchooserrectitem.cpp
  src/widget/widget.cpp
  src/widget/widget.h
  test/net/bsu_test.cpp
Labels: cleanup
