Repository TokTok/qTox, pull requests merged in 2025-03, with the labels that each got.

#566 docs: Translations update from Hosted Weblate
  translations/zh_TW.ts
Labels: documentation

#569 cleanup: Remove some unused headers.
  .ci-scripts/build-qtox-linux.sh
  .clang-tidy
  audio/src/backend/openal.h
  src/chatlog/content/filetransferwidget.cpp
  src/core/toxpk.cpp
  src/model/ichatlog.h
  src/model/message.cpp
  src/platform/autorun_osx.cpp
  src/platform/autorun_win.cpp
  src/platform/autorun_xdg.cpp
  src/platform/camera/avfoundation.mm
  src/platform/camera/v4l2.cpp
  src/platform/capslock_osx.cpp
  src/platform/capslock_win.cpp
  src/platform/capslock_x11.cpp
  src/platform/screenshot.cpp
  src/platform/screenshot_dbus.cpp
  src/platform/screenshot_dbus.h
  src/platform/timer_osx.cpp
  src/platform/timer_win.cpp
  src/platform/timer_x11.cpp
  src/platform/x11_display.cpp
  src/video/cameradevice.cpp
  src/video/camerasource.cpp
  src/widget/friendlistlayout.cpp
  src/widget/friendwidget.cpp
  src/widget/tool/callconfirmwidget.cpp
  test/chatlog/textformatter_test.cpp
  test/core/toxid_test.cpp
  test/persistence/paths_test.cpp
  test/persistence/serialize_fuzz_test.cpp
  tools/lsp_tidy.py
  util/src/algorithm.cpp
  util/src/ranges.cpp
Labels: cleanup

#563 fix(Startup): Allow Tox Address in the friend address settings.
  .gitignore
  CMakePresets.json
  src/core/toxpk.cpp
  src/persistence/settings.cpp
Labels: bug

#570 refactor: Make post-null cleanup code less trifa-specific.
  src/chatlog/chatmessage.cpp
  src/chatlog/textformatter.cpp
  src/chatlog/textformatter.h
  src/core/core.cpp
  src/core/toxstring.cpp
  src/core/toxstring.h
  src/model/notificationgenerator.cpp
  src/persistence/inotificationsettings.h
  src/persistence/settings.cpp
  src/persistence/settings.h
  src/platform/desktop_notifications/desktopnotify.cpp
  src/widget/form/settings/userinterfaceform.cpp
  src/widget/form/settings/userinterfaceform.h
  src/widget/form/settings/userinterfacesettings.ui
  test/chatlog/textformatter_test.cpp
  test/core/toxstring_test.cpp
  test/model/notificationgenerator_test.cpp
Labels: refactor

#571 docs: Translations update from Hosted Weblate
  translations/bg.ts
Labels: documentation

#568 cleanup: Push more code into generic settings functions.
  src/persistence/settings.cpp
  src/persistence/settings.h
Labels: cleanup

#521 test: Add a test for the identicon calculation.
  .gitignore
  cmake/Testing.cmake
  src/widget/tool/identicon.cpp
  src/widget/tool/identicon.h
  test/widget/tool/identicon_test.cpp
  tools/lsp_tidy.py
Labels: test

#574 cleanup: Add spaces to generated translations of MB/px.
  translations/ar.ts
  translations/ber.ts
  translations/bn.ts
  translations/da.ts
  translations/el.ts
  translations/eo.ts
  translations/he.ts
  translations/is.ts
  translations/ja.ts
  translations/jbo.ts
  translations/kn.ts
  translations/ko.ts
  translations/li.ts
  translations/lv.ts
  translations/mk.ts
  translations/si.ts
  translations/sl.ts
  translations/sq.ts
  translations/sw.ts
  translations/ug.ts
  translations/ur.ts
  translations/zh_CN.ts
  translations/zh_TW.ts
Labels: cleanup

#579 fix: Don't crash on chat log layout errors.
  src/chatlog/chatwidget.cpp
Labels: bug
